- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python3-ussuri-jobs
      - tempest-plugin-jobs
      - check-requirements
    gate:
      queue: ec2-api
